### ISSUE TITLE
Use GtkFileChooserNative

### ISSUE THREAD

**Issue by bbhtt** [mikacousin/olc#14]
OLC doesn't seem to use [GtkFileChooserNative](https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html) that supports [portal API](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser) but [GtkFileChooser](https://developer.gnome.org/gtk3/stable/GtkFileChooser.html)

https://github.com/mikacousin/olc/blob/dd3a70902d531a5c83faf070c3db45a204cdcdd4/src/application.py#L428

Portals allow to dynamically grant access to users rather than [hard-coding arbitrary filesystem access](https://github.com/flathub/com.github.mikacousin.olc/blob/6c99b4fb8068e29ae820a7b6771e6df79de80973/com.github.mikacousin.olc.json#L12) for example for an application. The primary benefit here is tighter sandboxing; also better desktop integration.

**Comment by bbhtt** [comment]
The other use is coming from OLA which seems to store the config files in ~/.ola. Are they needed?

If we want to suppress the warnings in https://github.com/mikacousin/olc/issues/15 a `--persist=.ola` needs to be added if removing the home directory access. That'd store any changes to the conf files when the sandbox is closed. Or maybe there is a way to change the defaults while building OLA?

Otherwise it is fine.

**Comment by mikacousin** [comment]
I'm looking at Gtk.FileChooserNative ASAP.
It seems to me a good solution to remove the access to home in the flatpak and when it is done, to add `--persist=.ola`
