### ISSUE TITLE
Virtual Console window is blank

### ISSUE THREAD

**Issue by gmeader** [mikacousin/olc#18]
I installed ola and olc on Lubuntu according to the directions in README.md
Version displayed in the About window: 0.6.beta
I do not know how to use it.
All the tabs are blank, except a few tabs have some table headings, such as Sequences, independents, Master List and Main Playback.
The Channels tab is empty.
Virtual Console is a blank window with a single digit 1 displayed.

**Comment by mikacousin** [comment]
Hello,

Can you post a screenshot of the main window and virtual console?
Can you start olc from a terminal and see if there are any errors ?

And is it possible for you to install the flathub version and see if the problem persists?

Thank you very much for your bug report.

**Comment by gmeader** [comment]
![screen02](https://user-images.githubusercontent.com/10481183/194981050-d79ceca4-0667-4c6a-a254-61b4956b07bb.jpg)
Screenshot of olc immediately after startup

![screen03vc](https://user-images.githubusercontent.com/10481183/194981339-16a514cc-6408-42bf-9af9-6bda6322c798.jpg)
Blank virtual Console - I just chose Virtual Console from the menu to get this window to appear

**Comment by gmeader** [comment]
Here's what is displayed when starting up from command line
glenn@glenn-linux:~/olc$ olc
common/io/IOUtils.cpp:39: open(/dev/dmx0): No such file or directory
plugins/opendmx/OpenDmxPlugin.cpp:81: Could not open /dev/dmx0 No such file or directory
common/io/IOUtils.cpp:39: open(/dev/kldmx0): No such file or directory
plugins/karate/KaratePlugin.cpp:80: Could not open /dev/kldmx0 No such file or directory
plugins/usbpro/UsbProWidgetDetector.cpp:323: USB Widget didn't respond to messages, esta id 0, device id 0
plugins/usbpro/UsbProWidgetDetector.cpp:326: Is device in USB Controller mode if it's a Goddard?
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

**Comment by gmeader** [comment]
I do not know anything about the flathub version. What is it and how do I install it?

**Comment by mikacousin** [comment]
> Here's what is displayed when starting up from command line
> glenn@glenn-linux:~/olc$ olc
> common/io/IOUtils.cpp:39: open(/dev/dmx0): No such file or directory
> plugins/opendmx/OpenDmxPlugin.cpp:81: Could not open /dev/dmx0
> No such file or directory common/io/IOUtils.cpp:39: open(/dev/kldmx0): No such file or directory
> plugins/karate/KaratePlugin.cpp:80: Could not open /dev/kldmx0 No such file or directory
> plugins/usbpro/UsbProWidgetDetector.cpp:323: USB Widget didn't respond to messages, esta id 0, device id 0
> plugins/usbpro/UsbProWidgetDetector.cpp:326: Is device in USB Controller mode if it's a Goddard?
> TypeError: Couldn't find foreign struct converter for 'cairo.Context'
> TypeError: Couldn't find foreign struct converter for 'cairo.Context'
> TypeError: Couldn't find foreign struct converter for 'cairo.Context'
> TypeError: Couldn't find foreign struct converter for 'cairo.Context'
> TypeError: Couldn't find foreign struct converter for 'cairo.Context'
> TypeError: Couldn't find foreign struct converter for 'cairo.Context'
> TypeError: Couldn't find foreign struct converter for 'cairo.Context'

First lines are about ola. Probably plugins that you can disable.

What interests us here are the errors `TypeError: Couldn't find foreign struct converter for 'cairo.Context'`.
After googling, you need to install the cairo python gobject interface.
I'm not using Lubuntu but you can try something like `sudo apt install python3-gi-cairo` and try to launch olc again (in terminal, to see errors)

**Comment by mikacousin** [comment]
> I do not know anything about the flathub version. What is it and how do I install it?

This is a package version that should work on any linux distribution.
See : https://flathub.org/apps/details/com.github.mikacousin.olc

**Comment by mikacousin** [comment]
Hi,
Did you try to install cairo python gobject interface and try olc again ?
I would like a confirmation before updating the doc and being able to close this issue.

**Comment by mikacousin** [comment]
Finally, I installed a virtual machine and I confirm that it's necessary to install python3-gi-cairo to solve this problem.
README updated accordingly.
