### ISSUE TITLE
Correcting English in po file

### ISSUE THREAD

**Issue by gmeader** [mikacousin/olc#22]
msgid "Rotatives Mode" should be "Rotation Mode"
msgid "+% et -% value" should be  "+% and -% value"

msgid "Sequence +" should be  "Next Sequence"
msgid "Sequence -" should be "Previous Sequence" or "Prev Sequence"

**Comment by mikacousin** [comment]
Hi,
Thanks for contributing.
My English is not very good, so any help is welcome.

> msgid "Rotatives Mode" should be "Rotation Mode"

Maybe "rotary encoder mode" would be clearer?

> msgid "+% et -% value" should be "+% and -% value"

Yes, typo

> msgid "Sequence +" should be "Next Sequence" msgid "Sequence -" should be "Previous Sequence" or "Prev Sequence"

These buttons are used to advance or rewind the sequence. So "Next step" and "Previous step" would be better.
